import { allEquals, allEqualsFactory } from "./allEquals";
import { allEqualsTo, allEqualsToFactory } from "./allEqualsTo";
import { allUniq, allUniqFactory } from "./allUniq";
import { and } from "./and";
import { includes } from "./includes";
import { count } from "./count";
import { every } from "./every";
import { or } from "./or";
import { removeDuplicates, removeDuplicatesFactory } from "./removeDuplicates";
import { sameAs, sameAsFactory } from "./sameAs";
import { partition } from "./partition";
import { diff } from "./diff";
export { allEquals, allEqualsFactory, allEqualsTo, allEqualsToFactory, allUniq, allUniqFactory, and, includes, count, every, or, removeDuplicates, removeDuplicatesFactory, sameAs, sameAsFactory, partition, diff };
